################################
# INFO: Keep this file as it is for testing purposes
#       Any new config files should be copied and not rewrite this file
################################
# 
# General part
#
# ############################

url: "https://localhost/test"
tokenuser: "test"
tokenpass: "test"
